//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microcolsa.Suite.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archivador
    {
        public Archivador()
        {
            this.mci_ArchvdresGrpo = new HashSet<mci_ArchvdresGrpo>();
            this.UsuariosArchivador = new HashSet<ArchivadoresUsuarios>();
            this.mci_PrmsoCmpo = new HashSet<mci_PrmsoCmpo>();
            this.mci_ArchvdorVncldo = new HashSet<mci_ArchvdorVncldo>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdTipoArchivador { get; set; }
        public string Nombre { get; set; }
        public string TituloArchivador { get; set; }
        public string FormatoFechaEntrada { get; set; }
        public string FormatoFechaSalida { get; set; }
        public byte MostrarFormularioConsulta { get; set; }
        public string CampoOrdenacion { get; set; }
        public string QueryAdicional { get; set; }
        public string ListaCamposSubConsulta { get; set; }
        public string QueryAdicionalSubConsulta { get; set; }
        public string CamposOcultar { get; set; }
        public string CamposOcultarFormulario { get; set; }
    
        public virtual TipoArchivador TipoArchivador { get; set; }
        public virtual ICollection<mci_ArchvdresGrpo> mci_ArchvdresGrpo { get; set; }
        public virtual ICollection<ArchivadoresUsuarios> UsuariosArchivador { get; set; }
        public virtual ICollection<mci_PrmsoCmpo> mci_PrmsoCmpo { get; set; }
        public virtual ICollection<mci_ArchvdorVncldo> mci_ArchvdorVncldo { get; set; }
    }
}
