//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microcolsa.Suite.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class mci_ArchvdresGrpo
    {
        public int intId { get; set; }
        public int intIdArchvdor { get; set; }
        public int intIdGrpo { get; set; }
        public byte intHbltdo { get; set; }
    
        public virtual Archivador mci_Archvdor { get; set; }
        public virtual mcu_Grpo mcu_Grpo { get; set; }
    }
}
