//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microcolsa.Suite.Core
{
    using System;
    using System.Collections.Generic;
    using Microcolsa.Suite.Core.General;
    
    public partial class mci_PrmsoCmpo
    {
        public int intId { get; set; }
        public Nullable<int> intIdUsrio { get; set; }
        public Nullable<int> intIdGrpo { get; set; }
        public int intIdArchvdor { get; set; }
        public string strCmpo { get; set; }
        public string strCndcnal { get; set; }
        public string strValor { get; set; }
    
        public virtual Archivador mci_Archvdor { get; set; }
        public virtual mcu_Grpo mcu_Grpo { get; set; }
        public virtual Usuario mcu_Usrio { get; set; }
    }
}
