//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microcolsa.Suite.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class mci_ArchvdorVncldo
    {
        public mci_ArchvdorVncldo()
        {
            this.mci_CmpoArchvdorVncldo = new HashSet<mci_CmpoArchvdorVncldo>();
        }
    
        public int intId { get; set; }
        public int intIdCnfgrcion { get; set; }
        public int intIdArchvdorPdre { get; set; }
    
        public virtual Archivador mci_Archvdor { get; set; }
        public virtual ICollection<mci_CmpoArchvdorVncldo> mci_CmpoArchvdorVncldo { get; set; }
    }
}
