//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microcolsa.Suite.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class mci_CmpoArchvdorVncldo
    {
        public int intId { get; set; }
        public int intIdCnfgrcion { get; set; }
        public int intIdArchvdorVncldo { get; set; }
        public string strCmpoPdre { get; set; }
        public string strCmpoVncldo { get; set; }
    
        public virtual mci_ArchvdorVncldo mci_ArchvdorVncldo { get; set; }
    }
}
