//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microcolsa.Suite.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class mcu_Dpndncia
    {
        public mcu_Dpndncia()
        {
            this.mcu_SbDpndncia = new HashSet<mcu_SbDpndncia>();
        }
    
        public int intId { get; set; }
        public int intIdEmprsa { get; set; }
        public string strNmbre { get; set; }
    
        public virtual mcu_Emprsa mcu_Emprsa { get; set; }
        public virtual ICollection<mcu_SbDpndncia> mcu_SbDpndncia { get; set; }
    }
}
