//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microcolsa.Suite.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class mcu_Dprtmnto
    {
        public mcu_Dprtmnto()
        {
            this.mcu_Cdad = new HashSet<mcu_Cdad>();
        }
    
        public int intId { get; set; }
        public int intIdPais { get; set; }
        public string strCdgo { get; set; }
        public string strNmbre { get; set; }
    
        public virtual ICollection<mcu_Cdad> mcu_Cdad { get; set; }
        public virtual mcu_Pais mcu_Pais { get; set; }
    }
}
