//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microcolsa.Suite.Core
{
    using System;
    using System.Collections.Generic;
    using Microcolsa.Suite.Core.General;
    
    public partial class mcu_SbDpndncia
    {
        public mcu_SbDpndncia()
        {
            this.mcu_Usrio = new HashSet<Usuario>();
        }
    
        public int intId { get; set; }
        public int intIdDpndncia { get; set; }
        public string strNmbre { get; set; }
    
        public virtual mcu_Dpndncia mcu_Dpndncia { get; set; }
        public virtual ICollection<Usuario> mcu_Usrio { get; set; }
    }
}
