//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microcolsa.Suite.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class mcu_Cdad
    {
        public mcu_Cdad()
        {
            this.mcu_Scrsal = new HashSet<mcu_Scrsal>();
        }
    
        public int intId { get; set; }
        public int intIdDprtmnto { get; set; }
        public string strCdgo { get; set; }
        public string strNmbre { get; set; }
    
        public virtual mcu_Dprtmnto mcu_Dprtmnto { get; set; }
        public virtual ICollection<mcu_Scrsal> mcu_Scrsal { get; set; }
    }
}
