//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microcolsa.Suite.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class mcu_Grpo
    {
        public mcu_Grpo()
        {
            this.mci_ArchvdresGrpo = new HashSet<mci_ArchvdresGrpo>();
            this.mci_PrmsoCmpo = new HashSet<mci_PrmsoCmpo>();
            this.mcu_GrpoUsrio = new HashSet<mcu_GrpoUsrio>();
        }
    
        public int intId { get; set; }
        public string strNmbre { get; set; }
        public string strDscrpcion { get; set; }
    
        public virtual ICollection<mci_ArchvdresGrpo> mci_ArchvdresGrpo { get; set; }
        public virtual ICollection<mci_PrmsoCmpo> mci_PrmsoCmpo { get; set; }
        public virtual ICollection<mcu_GrpoUsrio> mcu_GrpoUsrio { get; set; }
    }
}
