//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microcolsa.Suite.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class mcu_Scrsal
    {
        public mcu_Scrsal()
        {
            this.mcu_ScrslesUsrio = new HashSet<mcu_ScrslesUsrio>();
        }
    
        public int intId { get; set; }
        public int intIdCdad { get; set; }
        public string strNmbre { get; set; }
    
        public virtual mcu_Cdad mcu_Cdad { get; set; }
        public virtual ICollection<mcu_ScrslesUsrio> mcu_ScrslesUsrio { get; set; }
    }
}
