//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microcolsa.Suite.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoArchivador
    {
        public TipoArchivador()
        {
            this.Archivadores = new HashSet<Archivador>();
        }
    
        public int Id { get; set; }
        public int IdSubConfiguracion { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Archivador> Archivadores { get; set; }
        public virtual mci_SbCnfigDcwre mci_SbCnfigDcwre { get; set; }
        public virtual mci_SbCnfigMcrclsaDcments mci_SbCnfigMcrclsaDcments { get; set; }
        public virtual mci_SbCnfigShrePoint mci_SbCnfigShrePoint { get; set; }
    }
}
