//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microcolsa.Suite.Core.General
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.ArchivadoresUsuario = new HashSet<ArchivadoresUsuarios>();
            this.mci_PrmsoCmpo = new HashSet<mci_PrmsoCmpo>();
            this.mcu_GrpoUsrio = new HashSet<mcu_GrpoUsrio>();
            this.mcu_ScrslesUsrio = new HashSet<mcu_ScrslesUsrio>();
            this.mcu_Usrio1 = new HashSet<Usuario>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string Contrasena { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IdTipoIdentificacion { get; set; }
        public string Identificacion { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string Cargo { get; set; }
        public Nullable<int> IdSubDependencia { get; set; }
        public Nullable<int> IdCentroCosto { get; set; }
        public Nullable<int> IdUsuarioJefe { get; set; }
    
        public virtual ICollection<ArchivadoresUsuarios> ArchivadoresUsuario { get; set; }
        public virtual ICollection<mci_PrmsoCmpo> mci_PrmsoCmpo { get; set; }
        public virtual mcu_CCsto mcu_CCsto { get; set; }
        public virtual ICollection<mcu_GrpoUsrio> mcu_GrpoUsrio { get; set; }
        public virtual mcu_SbDpndncia mcu_SbDpndncia { get; set; }
        public virtual ICollection<mcu_ScrslesUsrio> mcu_ScrslesUsrio { get; set; }
        public virtual mcu_SgntreUsrio mcu_SgntreUsrio { get; set; }
        public virtual mcu_TpoIdntfccion mcu_TpoIdntfccion { get; set; }
        public virtual ICollection<Usuario> mcu_Usrio1 { get; set; }
        public virtual Usuario mcu_Usrio2 { get; set; }
    }
}
